### ISSUE TITLE
Releases.xml is not being updated anymore causes issues with .munki recipe

### ISSUE THREAD

**Issue by WardsParadox** [arubdesu/microsoft-recipes#19]
It seems like the Releases.xml is not being updated anymore past 16.17. This causes issues with the `.munki` recipe as the version is set to %NAME%-16.17 even though the latest version is 16.20.18120801. Removing the Version Processor and taking the `%version%` variable out of the filename argument for the URLDownloader fixes this issue with the MunkiImporter processor setting the version to 16.17. I'm doing some more testing to verify this 100%, but when I do, would you like me to submit a PR?

**Comment by arubdesu** [comment]
Would love a PR over at arubdesu/office-recipes, I should delete this repo…

**Comment by WardsParadox** [comment]
I realized that this weekend that I need to check that repo instead. Closing 👍
